# Generated by Django 3.2.5 on 2021-07-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriptions', models.TextField(verbose_name='Условия')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='rull',
        ),
        migrations.DeleteModel(
            name='Rull',
        ),
        migrations.AddField(
            model_name='discount',
            name='discric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discount.discriptions'),
            preserve_default=False,
        ),
    ]
