# Generated by Django 3.2.5 on 2021-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_review_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='order_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='order_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
